package com.akarinti.sapoe.objects

annotation class Params {
    companion object {
        const val BUNDLE_TEXT = "TEXT"
        const val BUNDLE_ACTION_TEXT = "ACTION_TEXT"
        const val BUNDLE_CANCEL_TEXT = "CANCEL_TEXT"
        const val BUNDLE_TAG = "TAG"
        const val BUNDLE_ICON = "ICON"
        const val BUNDLE_SCHEDULE = "schedule_object"
        const val BUNDLE_UNSCHEDULE = "manual_unschedule_object"
        const val BUNDLE_UNSCHEDULE_MANUAL = "manual_unschedule_object"
        const val BUNDLE_UNSCHEDULE_AUTO = "auto_unschedule_object"
        const val BUNDLE_QUESTION = "question_object"
        const val BUNDLE_CHECKLIST = "checklist_object"
        const val BUNDLE_QUESTION_DETAIL = "question_detail_object"
        const val BUNDLE_QUESTION_DETAIL_LIST = "question_detail_list_object"
        const val BUNDLE_ORDER_ID = "order_id"
        const val BUNDLE_SCHEDULE_ID = "schedule_id"
        const val BUNDLE_UNSCHEDULE_ID = "unschedule_id"
        const val BUNDLE_SCHEDULE_TYPE = "schedule_type"
        const val BUNDLE_TICKET_TYPE = "ticket_type"
        const val BUNDLE_ORDER_TYPE = "order_type"
        const val BUNDLE_SCHEDULE_CATEG = "schedule_categ"
        const val BUNDLE_SCHEDULE_FORM_IDX = "schedule_form_idx"
        const val BUNDLE_TICKET_FORM_IDX = "ticket_form_idx"
        const val BUNDLE_UNSCHEDULE_FORM_IDX = "unschedule_form_idx"
        const val BUNDLE_SCHEDULE_CHILD_IDX = "schedule_child_idx"
        const val BUNDLE_TICKET_CHILD_IDX = "ticket_child_idx"
        const val BUNDLE_TICKET_ITEMID = "ticket_item_id"
        const val BUNDLE_UNSCHEDULE_CHILD_IDX = "unschedule_child_idx"
        const val BUNDLE_SCHEDULE_QUESTION_IDX = "schedule_question_idx"
        const val BUNDLE_UNSCHEDULE_TYPE = "unschedule_type"
        const val BUNDLE_ITEM_ID = "item_id"
        const val BUNDLE_ITEM_INDEX = "item_index"
        const val BUNDLE_LOGIN = "login"
        const val BUNDLE_PARENT_AC = "object_p_ac"
        const val BUNDLE_PARENT_NB = "object_p_nb"
        const val BUNDLE_PARENT_CLEAN = "object_p_cl"
        const val BUNDLE_PARENT_OTHER = "object_p_other"
        const val BUNDLE_NEWS = "object_news"
        const val BUNDLE_FORCE_UPDATE = "flag_force_update"
        const val BUNDLE_APK_URL = "apk_url"
        const val BUNDLE_IMAGE_URL = "ticket_image_url"
        const val BUNDLE_ROUTE = "selected_route"
        const val BUNDLE_CITY_ID = "city_id"

        const val TAG_LOGIN = "LOGIN"
        const val TAG_TICKET = "TICKET"
        const val TAG_TAKE_TICKET = "TAKE_TICKET"
        const val TAG_CLOSE_TICKET = "CLOSE_TICKET"
        const val TAG_CREATE = "CONFIRM"
        const val TAG_TAKE = "TAKE"
        const val TAG_EXIT = "EXIT"
        const val TAG_REMOVE = "REMOVE"

        const val TYPE_NEONBOX = "nb"
        const val TYPE_AC = "ac"
        const val TYPE_CLEAN = "clean"
        const val TYPE_QC = "qc"
        const val TYPE_MCDS = "mcds"

        const val STATUS_OPEN = "open"
        const val STATUS_INPROGRESS = "inprogress"
        const val STATUS_UNSENT = "unsent"
        const val STATUS_COMPLETED = "completed"
        const val STATUS_CLOSED = "closed"

        const val CATEGORY_SCHEDULED = "scheduled"
        const val CATEGORY_UNSCHEDULED = "unscheduled"

        const val UNSCHEDULE_MANUAL = "manual"
        const val UNSCHEDULE_AUTO = "auto"

        const val QUESTION_PICTURE = "picture"
        const val QUESTION_COMBOBOX = "combobox"

        const val TYPE_PICTURE = "picture"

        const val USER_NAME = "username"
        const val IMAGE_BEFORE = "image_before"
        const val IMAGE_AFTER = "image_after"

        const val BUNDLE_TICKET = "ticket_object"
        const val BUNDLE_TICKET_ID = "ticket_id"
        const val BUNDLE_TICKET_INDEX = "ticket_index"

        const val BUNDLE_LAT = "lat"
        const val BUNDLE_LONG = "long"
    }
}